name: "Release"

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: "Deploy"
    runs-on: "ubuntu-22.04"

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y libgtk-4-dev libglib2.0-dev

      - name: Install cargo-deb
        run: cargo install cargo-deb

      - name: Build project
        run: cargo deb

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: ./target/debian/*.deb
